name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4001:4001"
      - "4002:4002"
    volumes:
      - hl-data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - hl-data:/home/hluser/hl/data


volumes:
  hl-data:
    driver: local
